[package]
name = "cshep"
description = "Command shepherd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3", default_features = false, features = ["derive", "std"] }
